version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: SFMovies.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  frontend:
    build:
      context: ./sfmovies-frontend  # Asumiendo que este será el directorio de tu frontend Vue
    ports:
      - "8080:80"
    depends_on:
      - backend